version: 2.1

orbs:
  docker: circleci/docker@1.4.0

executors:
  ruby-machine:
    # working_directory: ~/repo
    resource_class: medium
    docker:
      - image: circleci/ruby:2.6.5

commands:
#   dkr-cmd:
#     parameters:
#       dkr:
#         default: build
#         type: string
#     # resource_class: small
#     steps:
#       - run: docker login --username tymik --password $dockerhub_potenciales_token
#       - run: docker-compose <<parameters.dkr>>

# jobs:
#   build:
#     docker: 
#       - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
#     steps:
#       - checkout # check out the code in the project directory
#       - run: echo "hello world" # run the `echo` command

#   compose:
#     parameters:
#       compose-command:
#         default: build
#         type: string
#       steps:
#       executor:

  app_setup:
    steps:
      - setup_remote_docker:
          # docker_layer_caching: true
          version: 19.03.12
      - run:
          name: Build runtime environment
          command: docker-compose -f docker/circleci/docker-compose.yml up -d --build

jobs:
  playing-around:
    executor: ruby-machine
    steps:
      - checkout
      - app_setup
      - run:
          name: test-curl
          command: |
            docker image ls
            docker ps -a
            curl localhost
            curl localhost:8080/json/hostname

workflows:
  lint:
    jobs:
      - docker/hadolint:
          dockerfiles: ./frontend/Dockerfile.prod:./backend/Dockerfile

          
  build-and-publish-docker-image:
    jobs:
      - docker/publish:
          docker-context: ./backend
          dockerfile: ./backend/Dockerfile
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME_PYTHON_BE
          docker-username: CIRCLE_PROJECT_USERNAME
          docker-password: dockerhub_potenciales_token
          before_build:
            - checkout
      - docker/publish:
          docker-context: ./frontend
          dockerfile: ./frontend/Dockerfile.prod
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME_REACT_FE
          docker-username: CIRCLE_PROJECT_USERNAME
          docker-password: dockerhub_potenciales_token
          before_build:
            - checkout

  manual-build:
    jobs:
      - playing-around