version: '3.7'

services:

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.prod
    networks:
      - frontend
      - backend
    expose:
      - "80"
    volumes:
      - .:/code
    environment:
      VIRTUAL_HOST: frontend.local
      SOME_ENV: development

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    networks:
      - backend
    expose:
      - "8080"
    volumes:
      - .:/code
    environment:
      VIRTUAL_HOST: backend
      SOME_ENV: development

  nginx-proxy:
    image: jwilder/nginx-proxy
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      SOME_ENV: development

networks:
  frontend:
  backend:
  web:
    external: true
    name: bridge