version: '3.7'

services:

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.prod
    image: tymik/potenciales-react-frontend
    depends_on:
      - nginx-proxy
    networks:
      - frontend
      - backend
    expose:
      - "80"
    volumes:
      - .:/code
    environment:
      VIRTUAL_HOST: frontend.local
      # BACKEND_ADDRESS: backend

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    image: tymik/potenciales-python-backend
    depends_on:
      - nginx-proxy
    networks:
      - backend
    expose:
      - "8080"
    volumes:
      - .:/code
    environment:
      VIRTUAL_HOST: backend
      # ALLOW_ORIGIN: development

  nginx-proxy:
    image: jwilder/nginx-proxy
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      SOME_ENV: development
    extra_hosts:
      - "fronend.local:127.0.0.1"
      - "backend:127.0.0.1"


networks:
  frontend:
  backend: